### PR TITLE
fix: remove all returns the number of items removed

### LINKED ISSUE #1: RemoveAll extension should return number of items removed

### PR DESCRIPTION
**Pull request by thismaker**
This PR fixes #1

### CODE REVIEW

**Comment by PhyTensor** [comment]
Looks good

**Review by PhyTensor — APPROVED** [review]
Problemo solved

**Comment by thismaker** [comment]
you do the honours of merging it then :)

**Comment by PhyTensor** [comment]
Ohh sawasawa. I'd assumed it was a 'I review you merge, you review I
merge'. Merging it right away

**Pull request merged**
